[package]
name = "integration_tests"
version = "0.1.0"
authors = ["dkijania <dariusz.kijania@iohk.io>"]
edition = "2018"
build = "copy_files.rs"
links = "fs_extra"

[build-dependencies]
fs_extra = "1.1.0"

[dev-dependencies]
galvanic-test = "0.2.0"
assert_cmd = "0.11"
assert_fs = "0.11"
fs_extra = "1.1.0"
